# Generated by Django 4.1.7 on 2023-03-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('taskname', models.CharField(max_length=255)),
            ],
        ),
    ]
