# Generated by Django 4.1.7 on 2023-03-05 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
